name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image with Gradle
        run: ./gradlew bootBuildImage --imageName=${{ secrets.DOCKER_HUB_USERNAME }}/:${{ github.sha }}

      - name: Tag Docker image as latest
        run: docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/mnthly-money:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/mnthly-money:latest

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mnthly-money:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mnthly-money:latest
